namespace AuthService.Mcp;

public static class JwtConfigGenerator
{
    private const string UrlPlaceholder = "__AUTHSERVICE_URL__";
    private const string IssuerPlaceholder = "__AUTHSERVICE_ISSUER__";
    private const string HttpsMetadataPlaceholder = "__AUTHSERVICE_HTTPS_METADATA__";

    // JwtBearer refuses to fetch metadata over plain http unless told to, and authServiceUrl
    // defaults to http://localhost:8080 for local development.
    private const string HttpMetadataLines = """

                // authServiceUrl is plain http, which is only for local development. Remove this
                // line once it is https: over http, anyone on the path could swap the signing keys.
                options.RequireHttpsMetadata = false;
""";

    public static string Generate(string targetPath, ConsumerStack stack, string authServiceUrl, string issuer)
    {
        var url = NormalizeUrl(authServiceUrl);
        var (fileName, template) = stack switch
        {
            ConsumerStack.AspNetCore => ("AuthServiceJwt.cs", AspNetCoreTemplate),
            ConsumerStack.NodeExpress => ("authservice-auth.js", NodeExpressTemplate),
            ConsumerStack.PythonFastApi => ("authservice_auth.py", PythonFastApiTemplate),
            _ => throw new ArgumentOutOfRangeException(nameof(stack), stack, null),
        };

        var content = template
            .Replace(UrlPlaceholder, url)
            .Replace(IssuerPlaceholder, issuer)
            .Replace(HttpsMetadataPlaceholder, url.StartsWith("http://", StringComparison.Ordinal) ? HttpMetadataLines : "");

        var path = Path.Join(targetPath, fileName);
        File.WriteAllText(path, content);
        return path;
    }

    /// <summary>
    /// The URL as the generated code quotes it: absolute http or https, percent-encoded, with no
    /// trailing slash to double up against the well-known paths.
    /// </summary>
    public static string NormalizeUrl(string authServiceUrl)
    {
        if (!Uri.TryCreate(authServiceUrl, UriKind.Absolute, out var uri)
            || (uri.Scheme != Uri.UriSchemeHttp && uri.Scheme != Uri.UriSchemeHttps))
        {
            throw new ArgumentException(
                $"authServiceUrl '{authServiceUrl}' must be an absolute http or https URL.", nameof(authServiceUrl));
        }

        return uri.AbsoluteUri.TrimEnd('/');
    }

    // Mirrors README.md's "API overview" consumer snippet. RS256 needs no shared secret — only
    // this service's URL and the issuer and audience the compose file gives authservice.
    private const string AspNetCoreTemplate = """
// Generated by authservice's integrate tool — wire this into Program.cs:
//   builder.Services.AddAuthServiceJwtBearer();
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;

namespace AuthServiceIntegration;

public static class AuthServiceJwtExtensions
{
    public static IServiceCollection AddAuthServiceJwtBearer(this IServiceCollection services) =>
        services
            .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.MetadataAddress = "__AUTHSERVICE_URL__/.well-known/openid-configuration";__AUTHSERVICE_HTTPS_METADATA__
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = "__AUTHSERVICE_ISSUER__",
                    ValidAudience = "__AUTHSERVICE_ISSUER__",
                    ValidateIssuerSigningKey = true,
                };
            })
            .Services;
}
""";

    private const string NodeExpressTemplate = """
// Generated by authservice's integrate tool.
// npm install express-jwt jwks-rsa
const { expressjwt } = require("express-jwt");
const jwksRsa = require("jwks-rsa");

const authServiceJwt = expressjwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: "__AUTHSERVICE_URL__/.well-known/jwks.json",
  }),
  issuer: "__AUTHSERVICE_ISSUER__",
  audience: "__AUTHSERVICE_ISSUER__",
  algorithms: ["RS256"],
});

module.exports = { authServiceJwt };
""";

    private const string PythonFastApiTemplate = """
# Generated by authservice's integrate tool.
# pip install fastapi python-jose[cryptography] requests
from functools import lru_cache

import requests
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import jwt
from jose.exceptions import JOSEError

_AUTHSERVICE_URL = "__AUTHSERVICE_URL__"
_ISSUER = "__AUTHSERVICE_ISSUER__"
_AUDIENCE = "__AUTHSERVICE_ISSUER__"

_bearer = HTTPBearer()


@lru_cache(maxsize=1)
def _jwks() -> dict:
    return requests.get(f"{_AUTHSERVICE_URL}/.well-known/jwks.json", timeout=5).json()


def get_current_claims(credentials: HTTPAuthorizationCredentials = Depends(_bearer)) -> dict:
    try:
        return jwt.decode(
            credentials.credentials,
            _jwks(),
            algorithms=["RS256"],
            audience=_AUDIENCE,
            issuer=_ISSUER,
        )
    except JOSEError as exc:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid token") from exc
""";
}
