namespace AuthService.Mcp;

public static class JwtConfigGenerator
{
    private const string UrlPlaceholder = "__AUTHSERVICE_URL__";

    public static string Generate(string targetPath, ConsumerStack stack, string authServiceUrl)
    {
        var (fileName, template) = stack switch
        {
            ConsumerStack.AspNetCore => ("AuthServiceJwt.cs", AspNetCoreTemplate),
            ConsumerStack.NodeExpress => ("authservice-auth.js", NodeExpressTemplate),
            ConsumerStack.PythonFastApi => ("authservice_auth.py", PythonFastApiTemplate),
            _ => throw new ArgumentOutOfRangeException(nameof(stack), stack, null),
        };

        var path = Path.Join(targetPath, fileName);
        File.WriteAllText(path, template.Replace(UrlPlaceholder, authServiceUrl));
        return path;
    }

    // Mirrors README.md's "API overview" consumer snippet. RS256 needs no shared secret —
    // only this service's URL — so the generated file only ever needs an issuer/audience edit.
    private const string AspNetCoreTemplate = """
// Generated by authservice's integrate tool — wire this into Program.cs:
//   builder.Services.AddAuthServiceJwtBearer();
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.IdentityModel.Tokens;

namespace AuthServiceIntegration;

public static class AuthServiceJwtExtensions
{
    public static IServiceCollection AddAuthServiceJwtBearer(this IServiceCollection services) =>
        services
            .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                options.MetadataAddress = "__AUTHSERVICE_URL__/.well-known/openid-configuration";
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    ValidIssuer = "AuthService",
                    ValidAudience = "AuthService",
                    ValidateIssuerSigningKey = true,
                };
            })
            .Services;
}
""";

    private const string NodeExpressTemplate = """
// Generated by authservice's integrate tool.
// npm install express-jwt jwks-rsa
const { expressjwt } = require("express-jwt");
const jwksRsa = require("jwks-rsa");

const authServiceJwt = expressjwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: "__AUTHSERVICE_URL__/.well-known/jwks.json",
  }),
  issuer: "AuthService",
  audience: "AuthService",
  algorithms: ["RS256"],
});

module.exports = { authServiceJwt };
""";

    private const string PythonFastApiTemplate = """
# Generated by authservice's integrate tool.
# pip install fastapi python-jose[cryptography] requests
from functools import lru_cache

import requests
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import jwt
from jose.exceptions import JOSEError

_AUTHSERVICE_URL = "__AUTHSERVICE_URL__"
_ISSUER = "AuthService"
_AUDIENCE = "AuthService"

_bearer = HTTPBearer()


@lru_cache(maxsize=1)
def _jwks() -> dict:
    return requests.get(f"{_AUTHSERVICE_URL}/.well-known/jwks.json", timeout=5).json()


def get_current_claims(credentials: HTTPAuthorizationCredentials = Depends(_bearer)) -> dict:
    try:
        return jwt.decode(
            credentials.credentials,
            _jwks(),
            algorithms=["RS256"],
            audience=_AUDIENCE,
            issuer=_ISSUER,
        )
    except JOSEError as exc:
        raise HTTPException(status.HTTP_401_UNAUTHORIZED, "Invalid token") from exc
""";
}
